name: Build Release

on:
  push:
    branches:
      - "*.x"
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Fix gradlew file permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c
        with:
          arguments: app:distZip

      - name: Change binary file name
        run: mv ./app/build/distributions/app.zip ./app/build/distributions/${{github.ref_name}}-binary.zip

      - name: Calculate checksum of the file
        run: cd ./app/build/distributions && sha256sum ${{github.ref_name}}-binary.zip > sha256sums.txt && mv sha256sums.txt  ../../../

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./app/build/distributions/${{github.ref_name}}-binary.zip
            sha256sums.txt
